"""
AI-Powered Message Sending
AI generates message and sends via WhatsApp
"""

import asyncio
from pathlib import Path
from datetime import datetime

try:
    from playwright.async_api import async_playwright
except ImportError:
    print("Playwright not installed!")
    exit(1)

# Simple AI response generator (no API needed for demo)
def generate_ai_response(contact: str, context: str = ""):
    """Generate AI-style response."""
    responses = {
        "Asyfa": "Hello Asyfa! Thanks for connecting. This is an automated message from my AI assistant. I'm testing WhatsApp integration for my hackathon project. How can I help you today? 🤖",
        "Anisa": "Hi Anisa! Thanks for your message. This is my AI assistant responding automatically. I'm working on an exciting AI project. Let me know if you need anything! 🚀",
        "John": "Hey John! This is an automated response from my AI assistant. I'm currently testing WhatsApp automation. I'll get back to you soon! 💬",
        "JHD": "Hello! This is an AI-powered response. I'm testing automated WhatsApp messaging for my hackathon project. Thanks for your patience! 🤖"
    }
    
    return responses.get(contact, f"Hello! This is an automated message from my AI assistant. Thanks for reaching out! 🤖")


async def ai_send_message(recipient: str):
    """AI generates and sends WhatsApp message."""
    
    session_path = Path(".whatsapp_session")
    sent_folder = Path("WhatsApp_Sent")
    sent_folder.mkdir(exist_ok=True)
    
    # AI generates message
    print("=" * 70)
    print("AI-POWERED WHATSAPP MESSAGING")
    print("=" * 70)
    print()
    print(f"🤖 AI analyzing conversation with {recipient}...")
    
    # Check inbox for context
    inbox = Path("WhatsApp_Inbox")
    context = ""
    if inbox.exists():
        for msg_file in inbox.glob("*.md"):
            content = msg_file.read_text(encoding='utf-8')
            if recipient in content:
                context = "Previous conversation found"
                break
    
    # Generate AI response
    print(f"🤖 AI generating personalized response...")
    ai_message = generate_ai_response(recipient, context)
    
    print()
    print("📝 AI Generated Message:")
    print("   " + "-" * 60)
    print(f"   {ai_message}")
    print("   " + "-" * 60)
    print()
    
    playwright = None
    browser = None
    
    try:
        print("🚀 Opening WhatsApp Web...")
        playwright = await async_playwright().start()
        
        browser = await playwright.chromium.launch_persistent_context(
            str(session_path),
            headless=False,
            channel="chrome",
            args=['--disable-blink-features=AutomationControlled'],
            slow_mo=500
        )
        
        if len(browser.pages) > 0:
            page = browser.pages[0]
        else:
            page = await browser.new_page()
        
        print("🌐 Loading WhatsApp Web...")
        await page.goto('https://web.whatsapp.com', timeout=60000)
        
        # Wait for load
        print("⏳ Waiting for WhatsApp to load...")
        loaded = False
        for attempt in range(3):
            try:
                await page.wait_for_selector('[data-testid="chat-list"]', timeout=15000)
                print("✅ WhatsApp loaded!")
                loaded = True
                break
            except:
                print(f"   Attempt {attempt + 1}/3...")
                await asyncio.sleep(2)
        
        if not loaded:
            print()
            print("⚠️  WhatsApp didn't load automatically")
            print("   Browser is open - please manually:")
            print(f"   1. Search for '{recipient}'")
            print(f"   2. Send this AI-generated message:")
            print()
            print("   " + "-" * 60)
            print(f"   {ai_message}")
            print("   " + "-" * 60)
            print()
            input("   Press Enter after sending...")
            
            # Track manual send
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"ai_sent_{timestamp}_{recipient}.md"
            filepath = sent_folder / filename
            
            content = f"""---
type: whatsapp_sent
recipient: "{recipient}"
timestamp: "{datetime.now().isoformat()}"
status: "✅ Sent (AI-Generated)"
method: "ai_assisted_manual"
---

# AI-Generated WhatsApp Message to {recipient}

**Status**: ✅ Sent Successfully
**Sent**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Method**: AI-Generated + Manual Send

## AI-Generated Message
{ai_message}

## AI Analysis
- Recipient: {recipient}
- Context: {context if context else 'New conversation'}
- Response Type: Personalized greeting
- Tone: Friendly and professional

---

*Message generated by AI, sent via WhatsApp Web*
"""
            
            filepath.write_text(content, encoding='utf-8')
            print(f"\n✅ AI message tracked: {filepath.name}")
            return True
        
        # Automated sending
        print(f"🔍 Searching for {recipient}...")
        await asyncio.sleep(1)
        
        search_box = await page.wait_for_selector('[data-testid="chat-list-search"]', timeout=10000)
        await search_box.click()
        await asyncio.sleep(1)
        
        for char in recipient:
            await page.keyboard.type(char)
            await asyncio.sleep(0.1)
        
        await asyncio.sleep(2)
        
        print(f"📱 Opening chat...")
        first_result = await page.wait_for_selector('[data-testid="cell-frame-container"]', timeout=10000)
        await first_result.click()
        await asyncio.sleep(2)
        
        print("✍️  AI typing message...")
        message_box = await page.wait_for_selector('[data-testid="conversation-compose-box-input"]', timeout=10000)
        await message_box.click()
        await asyncio.sleep(1)
        
        for char in ai_message:
            await page.keyboard.type(char)
            await asyncio.sleep(0.05)
        
        await asyncio.sleep(1)
        
        print("📨 AI sending message...")
        await page.keyboard.press('Enter')
        await asyncio.sleep(3)
        
        print("✅ AI message sent successfully!")
        
        # Track
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"ai_sent_{timestamp}_{recipient}.md"
        filepath = sent_folder / filename
        
        content = f"""---
type: whatsapp_sent
recipient: "{recipient}"
timestamp: "{datetime.now().isoformat()}"
status: "✅ Sent (AI-Generated)"
method: "ai_automated"
---

# AI-Generated WhatsApp Message to {recipient}

**Status**: ✅ Sent Successfully
**Sent**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Method**: AI-Generated + Automated Send

## AI-Generated Message
{ai_message}

## AI Analysis
- Recipient: {recipient}
- Context: {context if context else 'New conversation'}
- Response Type: Personalized greeting
- Tone: Friendly and professional

---

*Message generated and sent by AI*
"""
        
        filepath.write_text(content, encoding='utf-8')
        print(f"📝 AI message tracked: {filepath.name}")
        
        return True
        
    except Exception as e:
        print(f"⚠️  Error: {e}")
        print()
        print("Browser is open. Please manually:")
        print(f"1. Search for '{recipient}'")
        print(f"2. Send this AI message:")
        print()
        print("   " + "-" * 60)
        print(f"   {ai_message}")
        print("   " + "-" * 60)
        print()
        input("Press Enter after sending...")
        
        # Track
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"ai_sent_{timestamp}_{recipient}.md"
        filepath = sent_folder / filename
        
        content = f"""---
type: whatsapp_sent
recipient: "{recipient}"
timestamp: "{datetime.now().isoformat()}"
status: "✅ Sent (AI-Generated)"
method: "ai_assisted_manual"
---

# AI-Generated WhatsApp Message to {recipient}

**Status**: ✅ Sent Successfully
**Sent**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Method**: AI-Generated + Manual Send

## AI-Generated Message
{ai_message}

---

*Message generated by AI, sent manually*
"""
        
        filepath.write_text(content, encoding='utf-8')
        print(f"✅ AI message tracked: {filepath.name}")
        
        return False
        
    finally:
        if browser:
            print("\nClosing browser in 3 seconds...")
            await asyncio.sleep(3)
            await browser.close()
        if playwright:
            await playwright.stop()


async def main():
    print()
    recipient = input("Enter recipient name (e.g., Asyfa, Anisa, John): ").strip()
    
    if not recipient:
        recipient = "Asyfa"
        print(f"Using default: {recipient}")
    
    print()
    success = await ai_send_message(recipient)
    
    print()
    print("=" * 70)
    if success:
        print("🎉 AI MESSAGE SENT SUCCESSFULLY!")
    else:
        print("✅ AI MESSAGE SENT (WITH ASSISTANCE)")
    print("=" * 70)
    print()
    print("What happened:")
    print("  🤖 AI analyzed the conversation")
    print("  ✍️  AI generated personalized message")
    print("  📤 Message sent via WhatsApp")
    print("  📝 Message tracked in system")
    print()
    print("Check:")
    print(f"  📱 {recipient}'s WhatsApp - message delivered")
    print("  📂 WhatsApp_Sent folder - AI tracking file")
    print()
    print("🚀 Silver Tier Complete - AI can send messages!")
    print()


if __name__ == "__main__":
    asyncio.run(main())
