"""
Main Loop

Entry point for the AI Employee System's periodic execution.
Triggered by the scheduler every 5 minutes.
"""

import sys
import logging
from pathlib import Path
from datetime import datetime

# Add Skills directory to path
sys.path.insert(0, str(Path(__file__).parent / "Skills"))

# Configure logging
log_dir = Path("Logs")
log_dir.mkdir(exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(log_dir / "main_loop.log"),
        logging.StreamHandler()
    ]
)

logger = logging.getLogger("main_loop")


def run_watchers():
    """
    Trigger all active watchers to check for new content.
    """
    logger.info("Running watchers...")
    
    # TODO: Import and run actual watchers when implemented
    # For now, this is a placeholder
    
    # Example:
    # from gmail_watcher import GmailWatcher
    # watcher = GmailWatcher()
    # watcher.check_for_new_items()
    
    logger.info("Watchers completed")


def process_inbox():
    """
    Process items in the Inbox folder.
    """
    logger.info("Processing inbox...")
    
    # TODO: Import and run Claude Code agent when implemented
    # For now, this is a placeholder
    
    # Example:
    # from claude_agent import ClaudeCodeAgent
    # agent = ClaudeCodeAgent()
    # agent.process_inbox()
    
    logger.info("Inbox processing completed")


def execute_plans():
    """
    Execute pending plans using Ralph Wiggum Loop.
    """
    logger.info("Executing plans...")
    
    # TODO: Import and run plan execution when implemented
    # For now, this is a placeholder
    
    # Example:
    # from plan_reasoning_loop import PlanReasoningLoop
    # loop = PlanReasoningLoop()
    # loop.execute_pending_plans()
    
    logger.info("Plan execution completed")


def update_dashboard():
    """
    Update Dashboard.md with current status.
    """
    logger.info("Updating dashboard...")
    
    # TODO: Implement dashboard update logic
    # For now, this is a placeholder
    
    dashboard_path = Path("Dashboard.md")
    
    if not dashboard_path.exists():
        # Create initial dashboard
        dashboard_content = f"""# AI Employee Dashboard

**Last Updated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## System Status
- Main Loop: Running
- Last Execution: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Today's Activity
- Watchers: Active
- Inbox Items: 0
- Plans Executed: 0

## Pending Actions
(None)

## Recent Completions
(None)

---
*Auto-generated by Main Loop*
"""
        dashboard_path.write_text(dashboard_content)
        logger.info("Dashboard created")
    else:
        # Update existing dashboard
        content = dashboard_path.read_text()
        
        # Update timestamp
        import re
        content = re.sub(
            r'\*\*Last Updated\*\*: .*',
            f'**Last Updated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}',
            content
        )
        
        # Update last execution
        content = re.sub(
            r'- Last Execution: .*',
            f'- Last Execution: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}',
            content
        )
        
        dashboard_path.write_text(content)
        logger.info("Dashboard updated")


def main():
    """
    Main execution loop.
    
    This function is called by the scheduler every 5 minutes.
    """
    logger.info("="*60)
    logger.info("MAIN LOOP STARTED")
    logger.info("="*60)
    
    try:
        # 1. Run watchers to detect new content
        run_watchers()
        
        # 2. Process inbox items
        process_inbox()
        
        # 3. Execute pending plans
        execute_plans()
        
        # 4. Update dashboard
        update_dashboard()
        
        logger.info("="*60)
        logger.info("MAIN LOOP COMPLETED SUCCESSFULLY")
        logger.info("="*60)
        
        return 0
    
    except Exception as e:
        logger.error(f"Main loop failed: {e}", exc_info=True)
        logger.info("="*60)
        logger.info("MAIN LOOP FAILED")
        logger.info("="*60)
        return 1


if __name__ == "__main__":
    sys.exit(main())
