"""
WhatsApp File-Based Integration - Silver Tier
Works without browser automation!

This system:
1. Monitors WhatsApp_Inbox/ for new messages
2. AI processes and generates responses
3. Saves responses to WhatsApp_Outbox/
4. User manually sends (or uses WhatsApp Business API later)
"""

import os
from pathlib import Path
from datetime import datetime
import json


class WhatsAppFileBased:
    """File-based WhatsApp integration that works without automation."""
    
    def __init__(self):
        self.inbox_dir = Path("WhatsApp_Inbox")
        self.outbox_dir = Path("WhatsApp_Outbox")
        self.sent_dir = Path("WhatsApp_Sent")
        self.processed_file = Path(".whatsapp_processed.json")
        
        # Create directories
        self.inbox_dir.mkdir(exist_ok=True)
        self.outbox_dir.mkdir(exist_ok=True)
        self.sent_dir.mkdir(exist_ok=True)
        
        # Load processed messages
        self.processed = self._load_processed()
    
    def _load_processed(self):
        """Load list of processed message IDs."""
        if self.processed_file.exists():
            return json.loads(self.processed_file.read_text())
        return []
    
    def _save_processed(self):
        """Save processed message IDs."""
        self.processed_file.write_text(json.dumps(self.processed, indent=2))
    
    def read_new_messages(self):
        """
        Read new messages from inbox.
        
        Returns:
            List of message dictionaries
        """
        messages = []
        
        for file in self.inbox_dir.glob("*.md"):
            if file.stem not in self.processed:
                content = file.read_text(encoding='utf-8')
                
                # Parse message
                message = {
                    'id': file.stem,
                    'file': str(file),
                    'content': content,
                    'timestamp': datetime.now().isoformat()
                }
                
                # Extract contact name from filename or content
                if '_from_' in file.stem:
                    message['from'] = file.stem.split('_from_')[1]
                
                messages.append(message)
                
                # Mark as processed
                self.processed.append(file.stem)
        
        if messages:
            self._save_processed()
            print(f"✅ Read {len(messages)} new messages")
        
        return messages
    
    def generate_response(self, message, response_text):
        """
        Generate a response for a message.
        
        Args:
            message: Message dictionary
            response_text: AI-generated response text
            
        Returns:
            Path to response file
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        contact = message.get('from', 'unknown')
        filename = f"response_{timestamp}_to_{contact}.md"
        filepath = self.outbox_dir / filename
        
        content = f"""---
type: whatsapp_response
to: "{contact}"
timestamp: "{datetime.now().isoformat()}"
status: "pending"
in_reply_to: "{message['id']}"
---

# WhatsApp Response to {contact}

**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Status**: Ready to send

## Original Message
{message['content']}

## AI Response
{response_text}

---

## Instructions
1. Copy the response above
2. Open WhatsApp Web
3. Find chat with {contact}
4. Paste and send
5. Move this file to WhatsApp_Sent/ when done

---

*Generated by AI Employee - Silver Tier*
"""
        
        filepath.write_text(content, encoding='utf-8')
        print(f"✅ Response generated: {filepath}")
        
        return filepath
    
    def mark_as_sent(self, response_file):
        """
        Mark a response as sent.
        
        Args:
            response_file: Path to response file
        """
        response_path = Path(response_file)
        
        if response_path.exists():
            # Move to sent folder
            sent_path = self.sent_dir / response_path.name
            
            # Update content
            content = response_path.read_text(encoding='utf-8')
            content = content.replace('status: "pending"', 'status: "sent"')
            content = content.replace('**Status**: Ready to send', '**Status**: ✅ Sent')
            
            sent_path.write_text(content, encoding='utf-8')
            response_path.unlink()
            
            print(f"✅ Marked as sent: {sent_path}")
            return sent_path
        
        return None
    
    def get_pending_responses(self):
        """Get list of pending responses to send."""
        return list(self.outbox_dir.glob("*.md"))
    
    def create_sample_message(self, contact, message_text):
        """
        Create a sample message in inbox for testing.
        
        Args:
            contact: Contact name
            message_text: Message text
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"message_{timestamp}_from_{contact}.md"
        filepath = self.inbox_dir / filename
        
        content = f"""---
type: whatsapp_message
from: "{contact}"
timestamp: "{datetime.now().isoformat()}"
---

# WhatsApp Message from {contact}

**Received**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Message
{message_text}

---

*Paste this from WhatsApp Web*
"""
        
        filepath.write_text(content, encoding='utf-8')
        print(f"✅ Sample message created: {filepath}")
        
        return filepath


def demo():
    """Demo the file-based system."""
    
    print("=" * 60)
    print("WhatsApp File-Based System - Silver Tier")
    print("=" * 60)
    
    wa = WhatsAppFileBased()
    
    print("\n1. Creating sample message...")
    wa.create_sample_message("Anisa", "Hello! How are you?")
    
    print("\n2. Reading new messages...")
    messages = wa.read_new_messages()
    
    if messages:
        print(f"\n3. Generating AI response...")
        for msg in messages:
            response = wa.generate_response(
                msg,
                "Hi! I'm doing great, thanks for asking! How about you?"
            )
            print(f"   Response saved to: {response}")
    
    print("\n4. Checking pending responses...")
    pending = wa.get_pending_responses()
    print(f"   Pending responses: {len(pending)}")
    
    print("\n" + "=" * 60)
    print("✅ File-Based System Working!")
    print("=" * 60)
    print("\nWorkflow:")
    print("1. Paste received messages in WhatsApp_Inbox/")
    print("2. AI reads and generates responses")
    print("3. Copy responses from WhatsApp_Outbox/")
    print("4. Send manually in WhatsApp Web")
    print("5. Mark as sent (moves to WhatsApp_Sent/)")
    print("\n" + "=" * 60)


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1:
        command = sys.argv[1].lower()
        wa = WhatsAppFileBased()
        
        if command == "read":
            messages = wa.read_new_messages()
            print(f"Read {len(messages)} new messages")
        
        elif command == "pending":
            pending = wa.get_pending_responses()
            print(f"Pending responses: {len(pending)}")
            for p in pending:
                print(f"  - {p.name}")
        
        elif command == "demo":
            demo()
        
        else:
            print("Commands: read, pending, demo")
    else:
        demo()
